#!/usr/bin/env bash

# Note that I don't recommend using source normally, you should insert the
# functions directly into your script.
# shellcheck disable=SC1091
source ../logger

log_fatal "this should be a fatal exit. Run \"echo \$?\" to get the exit status, which should be 1."
